// Mocks generated by Mockito 5.4.6 from annotations
// in tetris_flutter/test/data/repositories/game_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tetris_flutter/data/datasources/local_game_data_source.dart'
    as _i2;
import 'package:tetris_flutter/data/models/game_state_model.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [LocalGameDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalGameDataSource extends _i1.Mock
    implements _i2.LocalGameDataSource {
  MockLocalGameDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> saveGameState(_i4.GameStateModel? gameState) =>
      (super.noSuchMethod(
            Invocation.method(#saveGameState, [gameState]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<_i4.GameStateModel?> loadGameState() =>
      (super.noSuchMethod(
            Invocation.method(#loadGameState, []),
            returnValue: _i3.Future<_i4.GameStateModel?>.value(),
          )
          as _i3.Future<_i4.GameStateModel?>);

  @override
  _i3.Future<bool> hasSavedGame() =>
      (super.noSuchMethod(
            Invocation.method(#hasSavedGame, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> deleteSavedGame() =>
      (super.noSuchMethod(
            Invocation.method(#deleteSavedGame, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> autoSaveGameState(_i4.GameStateModel? gameState) =>
      (super.noSuchMethod(
            Invocation.method(#autoSaveGameState, [gameState]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<_i4.GameStateModel?> loadAutoSavedGameState() =>
      (super.noSuchMethod(
            Invocation.method(#loadAutoSavedGameState, []),
            returnValue: _i3.Future<_i4.GameStateModel?>.value(),
          )
          as _i3.Future<_i4.GameStateModel?>);

  @override
  _i3.Future<bool> clearAutoSavedGameState() =>
      (super.noSuchMethod(
            Invocation.method(#clearAutoSavedGameState, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> saveGameSettings(Map<String, dynamic>? settings) =>
      (super.noSuchMethod(
            Invocation.method(#saveGameSettings, [settings]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<Map<String, dynamic>> loadGameSettings() =>
      (super.noSuchMethod(
            Invocation.method(#loadGameSettings, []),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);
}
